### ISSUE TITLE
parse operation shouldn't save core data context

### ISSUE THREAD

**Issue by malhal** [inspace-io/INSOperationsKit#1]
I believe theres a mistake that the parse operation shouldn't save core data context because it might lead to the store being in an inconsistent state if the user has made changes to the context before the parse operation completes and then decides to throw away the changes rather than save.

**Comment by m1entus** [comment]
Parse operation is for demo purpose, it is fine because context is pased as a private context from main queue which need to be saved to be albe to see parsed data in main queue.
