### ISSUE TITLE
Build fails for tvOS

### ISSUE THREAD

**Issue by Frankacy** [inspace-io/INSOperationsKit#14]
When trying to add this pod to a tvOS project, the linker produces the following error:

ld: library not found for -lINSOperationsKit

I also tried building the tvOS demo in the example project. When doing so, I get a couple of errors:
- module.modulemap
  -- Umbrella header 'INSOperationsKit.h' not found
- INSDownloadOperation.h
  -- Could not build module 'INSOperationsKit'

Any immediate ideas of what the problem could be? I'll gladly try fixing it but I was hoping you could point me in the right direction first :)

(BTW: excellent work on this lib. I've been using this extensively in a new client project and it's working f'in great!)

**Comment by m1entus** [comment]
Thanks, glad you like it, we use it too and love to work with operations :)
