### ISSUE TITLE
INSMutallyExclusiveCondition petty fix

### ISSUE THREAD

**Issue by iostriz** [inspace-io/INSOperationsKit#16]
It is typo...
Mutually, not Mutally.
It is just my OCD, or better yet - CDO (sorted ascending).

br
Igor

**Comment by m1entus** [comment]
I just realised it today also.. Thanks for issue!

**Comment by matax87** [comment]
also some methods have these kind of typos

**Comment by m1entus** [comment]
Can you make pr for it ?
