### ISSUE TITLE
Umbrella header missing from Cocoapods install

### ISSUE THREAD

**Issue by craigmarvelley** [inspace-io/INSOperationsKit#4]
Hi,

As a result of https://github.com/inspace-io/INSOperationsKit/commit/3fc5669b6b673c5b3e90ffd37f575ffd5a265cc8 the INSOperationsKit.h umbrella header is no longer included in the library when installed through Cocoapods. Is this intentional? 

If I need to create one for my own project that's fine, just want to check there's not a better way to include all the files in the library before I go ahead and do that.

Cheers!

**Comment by m1entus** [comment]
Yes, new cocoapods 1.0.0 beta 4 probably is doing it for you, and i have errors that files are missing or sth. Just check previous version on newest cocoapods and you will see :/ Nit sure if this is a bug or no need anymore to have umbrella header

**Comment by craigmarvelley** [comment]
OK, so I updated to `1.1.0 beta 4` of Cocoapods (was previously on `0.39.0`) and I'm on `1.1.2` of INSOperationsKit. Same issue. Maybe i'm not understanding the diff right, but it looks to me like the shared header file was removed? Is that not the issue here?

**Comment by craigmarvelley** [comment]
Might it be that the source config in the pod spec is loading files from  `s.ios.source_files = 'INSOperationsKit/Shared/**/*.{h,m}', 'INSOperationsKit/iOS/**/*.{h,m}'` - but the only header file in that vicinity is located at `INSOperationsKit/INSOperationsKit.h`?

**Comment by craigmarvelley** [comment]
Altered the podspec in my fork as per the above PR which has got it working for me for now at least. If it's not the right approach obviously feel free to close, I don't know much about Cocoapods :)

**Comment by m1entus** [comment]
Ok i have added it.
