### ISSUE TITLE
Errors reported when conditions fail are not passed to operation completion block.

### ISSUE THREAD

**Issue by BennettSmith** [inspace-io/INSOperationsKit#9]
Looking at the evaluateConditions method in INSOperation.m (line 121) I do not believe failures ever has a count other than zero.  It appears that conditions should call the cancel method on their operation when the condition is not met.  Currently the conditions provided in INSOperationsKit do not call cancel.

Am I understanding this correctly, or is there another way to pass errors back from conditions?

Thanks

**Comment by m1entus** [comment]
This is correct and you could make a condition which will check if dependencies have some errors and cancel it and pass error. I already did something like that in my custom project, i will try to update this library and add it

**Comment by m1entus** [comment]
Failures can have count other than zero if INSOperationConditionResult object will contain error, check INSOperationConditionResult.m (line 66)
